name: startup-stage-calculator
region: sfo
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: jhillbht/startup-stage-calculator
  health_check:
    http_path: /
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: startup-stage-calculator
  routes:
  - path: /
  run_command: npm start
  source_dir: /
  envs:
  - key: NEXT_PUBLIC_APP_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: NEXT_PUBLIC_API_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}/api
  - key: NEXT_PUBLIC_DEALS_CSV_URL
    scope: RUN_AND_BUILD_TIME
    value: https://raw.githubusercontent.com/jhillbht/startup-stage-calculator/main/data/deals.csv